# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ClDouYSc2ZJoPLjFhmvNLc6PJG4kpega
"""

import pandas as pd
baza={
 "FISH":[ "Salimova Laylo","Murodov Suhrob", "Anavarova Guli", "Islomov Yusuf" ],
 "Yoshi":[ "18", "20", "16", '17'  ],
 "Jinsi":[ "qiz bola" , "o‘g‘il bola" ,"qiz bola" , "o‘g‘il bola" ],
 "Qaysi universitetda o‘qishi":[ "KIUF", "FARPI","TATUFF","FARDU"  ],
 "Manzili":[ "Qo‘qon", "Farg‘ona", "Andijon", "Namangan"  ]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="qiz bola"]
print(filtr)

filtr=db[db['Manzili']=="Farg‘ona"]
print(filtr)

filtr=db[(db['Jinsi']=="o‘g‘il bola")&(db["Yoshi"]>'18')]
print(filtr)





